# SPDX-License-Identifier: MIT
"""Generate example-based documentation for ellipsoid_psf.

For every program in examples/, this script runs the built executable in a
scratch directory, captures its stdout and any figures it writes, copies the
figures to docs/img/, and emits docs/examples/<name>.md showing the program,
its output, and its figures ("show, don't tell").

The generated markdown is committed. CI re-runs this script with --check,
which fails if any committed page differs from what the code actually
produces — so the documentation cannot drift from the library. Figure image
bytes are exempt from the check (tiny floating-point differences across
toolchains would make them flaky); the figures are still regenerated and
committed from the maintainer machine.

Usage:
    python3 docs/generate_examples.py [--build-dir build] [--check]
"""

import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
EXAMPLES_DIR = REPO / "examples"
DOCS_DIR = REPO / "docs"
PAGES_DIR = DOCS_DIR / "examples"
IMG_DIR = DOCS_DIR / "img"


def split_intro(source: str):
    """Leading '//' comment block -> (title, intro_markdown, remaining_source)."""
    lines = source.splitlines()
    intro = []
    body_start = 0
    for i, line in enumerate(lines):
        if line.startswith("//"):
            intro.append(line[2:].lstrip())
        else:
            body_start = i
            break
    while body_start < len(lines) and lines[body_start].strip() == "":
        body_start += 1
    title = intro[0] if intro else "Example"
    intro_md = "\n".join(intro[1:]).strip()
    return title, intro_md, "\n".join(lines[body_start:])


def run_example(exe: Path, scratch: Path) -> tuple[str, list[Path], dict[str, str]]:
    result = subprocess.run([str(exe)], cwd=scratch, capture_output=True, text=True, timeout=600)
    if result.returncode != 0:
        sys.exit(f"example {exe.name} failed:\n{result.stdout}\n{result.stderr}")
    figures = sorted(p for p in scratch.iterdir() if p.suffix in (".svg", ".png"))
    # A figure may write a caption next to itself as <stem>.caption.md; the
    # caption is emitted above the image (and, unlike figure bytes, IS
    # covered by the freshness check).
    captions = {}
    for fig in figures:
        caption_file = fig.with_name(fig.stem + ".caption.md")
        if caption_file.exists():
            captions[fig.name] = caption_file.read_text().strip()
    return result.stdout, figures, captions


def build_page(name: str, title: str, intro: str, body: str, stdout: str,
               figure_names: list[str], captions: dict[str, str]) -> str:
    parts = [f"# {title}", ""]
    if intro:
        parts += [intro, ""]
    if figure_names:
        parts += ["## Figures", ""]
        for fig in figure_names:
            if fig in captions:
                parts += [captions[fig], ""]
            parts += [f"![{fig}](../img/{name}__{fig})", ""]
    parts += ["## Program", "", "```cpp", body.rstrip(), "```", ""]
    parts += ["## Output", "", "```text", stdout.rstrip(), "```", ""]
    parts += ["---", "",
              "*This page is generated by `docs/generate_examples.py` from "
              f"[`examples/{name}.cpp`](../../examples/{name}.cpp); "
              "the output and figures above are produced by actually running it.*", ""]
    return "\n".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--build-dir", default="build")
    parser.add_argument("--check", action="store_true",
                        help="fail if regenerating changes any committed page")
    args = parser.parse_args()

    build_dir = (REPO / args.build_dir).resolve()
    PAGES_DIR.mkdir(parents=True, exist_ok=True)
    IMG_DIR.mkdir(parents=True, exist_ok=True)

    names = sorted(p.stem for p in EXAMPLES_DIR.glob("*.cpp"))
    index_lines = ["# ellipsoid_psf examples", "",
                   "Each page shows a complete program, its actual output, and the "
                   "figures it draws — all regenerated from the code by "
                   "`docs/generate_examples.py`.", ""]

    for name in names:
        exe = build_dir / "examples" / name
        if not exe.exists():
            sys.exit(f"missing executable {exe}; build with -DELLIPSOID_PSF_BUILD_EXAMPLES=ON first")
        source = (EXAMPLES_DIR / f"{name}.cpp").read_text()
        title, intro, body = split_intro(source)

        with tempfile.TemporaryDirectory() as tmp:
            scratch = Path(tmp)
            stdout, figures, captions = run_example(exe, scratch)
            figure_names = []
            for fig in figures:
                target = IMG_DIR / f"{name}__{fig.name}"
                shutil.copyfile(fig, target)
                figure_names.append(fig.name)

        page = build_page(name, title, intro, body, stdout, figure_names, captions)
        (PAGES_DIR / f"{name}.md").write_text(page)
        index_lines.append(f"- [{title}](examples/{name}.md)")
        print(f"generated docs/examples/{name}.md ({len(figure_names)} figures)")

    # Hand-written notes get an index section too (their titles are read from
    # the first heading), so the whole README stays generated and the
    # freshness check covers it.
    notes = sorted((DOCS_DIR / "notes").glob("*.md"))
    if notes:
        index_lines += ["", "## Notes", "",
                        "Hand-written notes on behavior worth knowing about (not generated):", ""]
        for note in notes:
            first_line = note.read_text().splitlines()[0].strip()
            title = first_line.lstrip("#").strip() if first_line.startswith("#") else note.stem
            index_lines.append(f"- [{title}](notes/{note.name})")

    index_lines += [""]
    (DOCS_DIR / "README.md").write_text("\n".join(index_lines))

    if args.check:
        diff = subprocess.run(
            ["git", "diff", "--exit-code", "--", "docs/README.md", "docs/examples"],
            cwd=REPO)
        if diff.returncode != 0:
            sys.exit("documentation is stale: regenerate with docs/generate_examples.py and commit")
        print("documentation is up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
